#!/bin/sh
mkdir -p "$HOME/.zoombie/bin/zoombie"
git clone "https://github.com/DaBigBlob/zoombie.git" "$HOME/.zoombie/bin/zoombie"
touch "$HOME/zoom-meetings.txt"

export PATH="$PATH:$HOME/.zoombie/bin"
printf "#added my zoombie installer\n$PATH:%s\n" "$HOME/.zoombie/bin" >> "$HOME/.profile"

printf "Installed.\n"

